#!/usr/bin/env python3
"""Regenerate index_html_gz.h from the INDEX_HTML literal in the sketch.

The browser UI lives as one raw string literal inside
wdi_esp32_cam_robot_m2.ino so the sketch still opens in the Arduino IDE with
no extra steps. That literal is ~65 KB and it is served over the same Wi-Fi
link as the video, so the firmware serves a gzipped copy instead.

Run this after editing the HTML, CSS, or JavaScript in the sketch:

    python tools/gzip_ui.py

The generated header is committed. If you forget to run this, the firmware
notices at boot -- it compares the length and hash recorded here against the
literal it was built with -- and falls back to serving the page uncompressed
rather than serving a stale UI.
"""

import gzip
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SKETCH = os.path.join(ROOT, "wdi_esp32_cam_robot_m2.ino")
HEADER = os.path.join(ROOT, "index_html_gz.h")

OPEN_MARK = 'R"rawliteral('
CLOSE_MARK = ')rawliteral";'


def fnv1a32(data):
    """Same hash the firmware computes over INDEX_HTML at boot."""
    h = 2166136261
    for b in data:
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h


def extract_html(source):
    start = source.find(OPEN_MARK)
    if start < 0:
        raise SystemExit("No raw string literal found in " + SKETCH)

    start += len(OPEN_MARK)
    end = source.find(CLOSE_MARK, start)
    if end < 0:
        raise SystemExit("Unterminated raw string literal in " + SKETCH)

    return source[start:end]


def format_bytes(blob):
    lines = []
    for offset in range(0, len(blob), 12):
        chunk = blob[offset:offset + 12]
        lines.append("  " + " ".join("0x%02x," % b for b in chunk))
    return "\n".join(lines)


def main():
    source = io.open(SKETCH, encoding="utf-8", newline="").read()
    html = extract_html(source)

    # The firmware serves strlen(INDEX_HTML) bytes, and the compiler stores
    # the literal with LF line endings, so hash exactly those bytes.
    raw = html.encode("utf-8")

    # mtime=0 keeps the output byte-identical between runs, so the committed
    # header only changes when the UI actually changes.
    buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=buffer, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(raw)
    blob = buffer.getvalue()

    header = (
        "// Generated by tools/gzip_ui.py -- do not edit by hand.\n"
        "//\n"
        "// A gzipped copy of the INDEX_HTML literal in\n"
        "// wdi_esp32_cam_robot_m2.ino. Re-run the tool after changing the UI;\n"
        "// the firmware falls back to the uncompressed literal if this file is\n"
        "// stale.\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n"
        "\n"
        "// Length and FNV-1a hash of the literal this was generated from.\n"
        "static const size_t INDEX_HTML_SOURCE_LEN = %d;\n"
        "static const uint32_t INDEX_HTML_SOURCE_HASH = 0x%08xUL;\n"
        "\n"
        "static const size_t INDEX_HTML_GZ_LEN = %d;\n"
        "\n"
        "static const unsigned char INDEX_HTML_GZ[] PROGMEM = {\n"
        "%s\n"
        "};\n"
    ) % (len(raw), fnv1a32(raw), len(blob), format_bytes(blob))

    io.open(HEADER, "w", encoding="utf-8", newline="\n").write(header)

    print("UI literal   : %d bytes" % len(raw))
    print("gzipped      : %d bytes (%.1f%% of the original)"
          % (len(blob), 100.0 * len(blob) / len(raw)))
    print("written      : %s" % HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
